export const theme = {
  colors: {
    primary: '#D2691E',
    primaryDark: '#B8541A',
    secondary: '#8B4513',
    accent: '#F4A460',
    background: '#FFF8F0',
    surface: '#FFFFFF',
    text: '#2C1810',
    textSecondary: '#5D4037',
    textMuted: '#8D6E63',
    success: '#4CAF50',
    error: '#F44336',
    border: '#E0E0E0',
    shadow: 'rgba(45, 24, 16, 0.1)',
  },
  fonts: {
    regular: 'System',
    medium: 'System',
    bold: 'System',
  },
  fontSizes: {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 18,
    xl: 20,
    xxl: 24,
    xxxl: 28,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 20,
    xl: 24,
    xxl: 32,
  },
  borderRadius: {
    sm: 6,
    md: 8,
    lg: 12,
    xl: 16,
  },
  shadows: {
    sm: {
      shadowColor: '#2C1810',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    md: {
      shadowColor: '#2C1810',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 4,
    },
  },
};